/** Personal site copy (edit freely). */
export const site = {
  /** Legal / formal name */
  name: 'Chisom Chiobi J',
  /** Handle for nav, GitHub vibe, etc. */
  nickname: 'jasonthe_dev',
  role: 'Software engineer · University of Alberta, Class of 2026',
  tagline:
    "I'm a software engineer based in Canada. I like shipping things that work: web apps, small tools, and the occasional plugin. Lately that's meant a lot of Vue, FastAPI, and Java, with a boring (in a good way) focus on clear UI and backends that don't fall over.",
  location: 'Based in Canada · B.Sc. Computer Science, University of Alberta',
  profilePhoto: '/profile.png',
  resumeUrl: '/Chisom_Chiobi_Resume.pdf',
  email: 'chisomchiobi@gmail.com',
  phone: '(780) 226-7277',
  social: [
    { label: 'LinkedIn', href: 'https://www.linkedin.com/in/chisom-chiobi/' },
    { label: 'GitHub', href: 'https://github.com/ChiobiJason' },
    { label: 'X', href: 'https://x.com/jasonthe_dev' },
  ],
}

/** Projects. `repo` and `live` are optional. `featured` controls the top 3 on the home page. */
export const projects = [
  {
    id: 'a2cs-fashion-show-2026',
    title: 'A2CS Fashion Show 2026',
    summary:
      'A premium event site with glassmorphism, scroll reveals, and a punchy hero. Built as a high-end digital experience with Vue 3 and Vite.',
    tags: ['Vue 3', 'Vite', 'CSS', 'Intersection Observer'],
    repo: 'https://github.com/ChiobiJason/A2CS-Fashion-Show-2026',
    live: 'https://a2-cs-fashion-show-2026.vercel.app/',
    screenshot: '/screenshots/a2cs-fashion-show-2026.png',
    featured: true,
    homeOrder: 2,
    accent: 'linear-gradient(135deg, #1d1d1f 0%, #2d2d2f 100%)',
  },
  {
    id: 'augustana-futsal-winter-2026',
    title: 'Augustana Futsal Winter 2026 Tournament',
    summary:
      'Team registration website with tournament rules and real-time event info. Submissions go straight into Google Sheets using a Google Apps Script endpoint.',
    tags: ['Vue 3', 'Vite', 'Google Sheets', 'Google Apps Script'],
    repo: 'https://github.com/ChiobiJason/Augustana-Futsal-Winter-2026-Tournament',
    live: 'https://augustana-futsal-winter-2026-tourna.vercel.app/',
    screenshot: '/screenshots/augustana-futsal-winter-2026.png',
    featured: true,
    homeOrder: 3,
    accent: 'linear-gradient(135deg, #0071e3 0%, #2997ff 100%)',
  },
  {
    id: 'asa-inventory-frontend',
    title: 'ASA Inventory App (Frontend)',
    summary:
      'Inventory management SPA with dashboards, tables, product detail views, and admin tooling. Includes auth guard, onboarding emails, and a Render spin-up overlay.',
    tags: ['Vue 3', 'Vite', 'Vue Router', 'Vuex', 'Axios', 'Chart.js'],
    repo: 'https://github.com/augustanastudents2/Inventory-App-Frontend',
    live: 'https://inventory-app-frontend-lilac.vercel.app',
    screenshot: '/screenshots/asa-inventory-frontend.png',
    featured: true,
    homeOrder: 4,
    rank: 2,
    accent: 'linear-gradient(135deg, #6e6e73 0%, #aeaeb2 100%)',
  },
  {
    id: 'asa-inventory-backend',
    title: 'ASA Inventory App (Backend)',
    summary:
      'Backend API for inventory management with role-based access and settings for categories, tags, vendors, and storage. Deployed on Render.',
    tags: ['FastAPI', 'PostgreSQL', 'Supabase', 'REST', 'RBAC'],
    repo: 'https://github.com/augustanastudents2/Inventory-App-Backend',
    live: 'https://inventory-app-backend-yftf.onrender.com/docs',
    screenshot: '/screenshots/asa-inventory-backend-docs.png',
    featured: false,
    rank: 4,
    accent: 'linear-gradient(135deg, #2d2d2f 0%, #636366 100%)',
  },
  {
    id: 'asa-policy-frontend',
    title: 'ASA Policy App (Frontend)',
    summary:
      'Student-facing policy and bylaw pages plus an admin panel for creating, editing, and approving content. Built as plain HTML, CSS, and JS with Quill and PDF support.',
    tags: ['HTML', 'CSS', 'JavaScript', 'Quill', 'jsPDF', 'Vercel'],
    repo: 'https://github.com/augustanastudents2/Policy-App-Frontend',
    live: 'https://policy-app-frontend-five.vercel.app/',
    screenshot: '/screenshots/asa-policy-frontend.png',
    featured: true,
    homeOrder: 1,
    rank: 1,
    accent: 'linear-gradient(135deg, #1d1d1f 0%, #424245 100%)',
  },
  {
    id: 'asa-policy-backend',
    title: 'ASA Policy App (Backend)',
    summary:
      'Backend API for ASA policy and bylaw management, powering public views and admin workflows. Deployed on Render.',
    tags: ['FastAPI', 'REST', 'Render'],
    repo: 'https://github.com/augustanastudents2/Policy-App-Backend',
    live: 'https://policy-app-backend.onrender.com/docs',
    screenshot: '/screenshots/asa-policy-backend-docs.png',
    featured: false,
    rank: 3,
    accent: 'linear-gradient(135deg, #0071e3 0%, #2997ff 100%)',
  },
  {
    id: 'tindog',
    title: 'TinDog',
    summary:
      'Playful single-page landing page concept with a clean Bootstrap layout and responsive sections.',
    tags: ['HTML', 'CSS', 'Bootstrap'],
    repo: 'https://github.com/ChiobiJason/TinDog',
    live: 'https://chiobijason.github.io/TinDog/',
    screenshot: '/screenshots/tindog.png',
    featured: false,
    rank: 15,
    accent: 'linear-gradient(135deg, #6e6e73 0%, #aeaeb2 100%)',
  },
  {
    id: 'augustana-hub-frontend',
    title: 'Augustana Hub (Frontend)',
    summary:
      'React frontend for a student discovery platform. Profile registration plus a clean, filterable interface backed by a Spring Boot API.',
    tags: ['React', 'TypeScript', 'REST'],
    repo: 'https://github.com/ChiobiJason/augustana-hub-frontend',
    live: null,
    screenshot: '/screenshots/augustana-hub-frontend.png',
    featured: false,
    rank: 7,
    accent: 'linear-gradient(135deg, #1d1d1f 0%, #2d2d2f 100%)',
  },
  {
    id: 'augustana-hub-backend',
    title: 'Augustana Hub (Backend)',
    summary:
      'Spring Boot and PostgreSQL backend for a student directory API with registration and filtering (v1 without auth).',
    tags: ['Spring Boot', 'PostgreSQL', 'REST', 'Java'],
    repo: 'https://github.com/ChiobiJason/augustana-hub-backend',
    live: null,
    screenshot: '/screenshots/augustana-hub-backend.png',
    featured: false,
    rank: 8,
    accent: 'linear-gradient(135deg, #0071e3 0%, #2997ff 100%)',
  },
  {
    id: 'anti-ai-intellij-plugin',
    title: 'Anti-AI IntelliJ Plugin',
    summary:
      'Directed study project: an IntelliJ plugin that disables AI assist features and keeps them off for the session.',
    tags: ['Java', 'IntelliJ Platform', 'Plugin'],
    repo: 'https://github.com/ChiobiJason/AUCSC-395',
    live: null,
    screenshot: '/screenshots/anti-ai-intellij-plugin-5.png',
    featured: false,
    rank: 9,
    accent: 'linear-gradient(135deg, #2d2d2f 0%, #636366 100%)',
  },
  {
    id: 'the-other-side',
    title: 'The Other Side',
    summary:
      'Fast-paced Android dodge-and-collect game built in Java with swipe movement, obstacles, scoring, and a modular team-built architecture.',
    tags: ['Android', 'Java', 'Game'],
    repo: 'https://github.com/ChiobiJason/TheOtherSide',
    live: null,
    screenshot: '/screenshots/the-other-side.png',
    featured: false,
    rank: 10,
    accent: 'linear-gradient(135deg, #1d1d1f 0%, #424245 100%)',
  },
  {
    id: 'mfm-gh-teens',
    title: 'MFM GH Teens',
    summary:
      'Responsive youth church website built with HTML, CSS, Bootstrap, and jQuery for announcements and engagement.',
    tags: ['HTML', 'CSS', 'Bootstrap', 'JavaScript', 'jQuery'],
    repo: 'https://github.com/ChiobiJason/Mfm-Gh-Teens',
    live: 'https://chiobijason.github.io/Mfm-Gh-Teens/',
    screenshot: '/screenshots/mfm-gh-teens.png',
    featured: false,
    rank: 13,
    accent: 'linear-gradient(135deg, #6e6e73 0%, #aeaeb2 100%)',
  },
  {
    id: 'nft-site',
    title: 'NFT Site',
    summary: 'Marketing site for the Meta-Pigeon Sneaker NFT drop.',
    tags: ['HTML', 'CSS', 'JavaScript'],
    repo: 'https://github.com/ChiobiJason/NFT-Site',
    live: 'https://chiobijason.github.io/NFT-Site/',
    screenshot: '/screenshots/nft-site.png',
    featured: false,
    rank: 12,
    accent: 'linear-gradient(135deg, #2d2d2f 0%, #636366 100%)',
  },
  {
    id: 'password-generator',
    title: 'Password Generator',
    summary: 'Small web app that generates passwords with a simple UI.',
    tags: ['JavaScript', 'HTML', 'CSS'],
    repo: 'https://github.com/ChiobiJason/Password-Generator',
    live: 'https://chiobijason.github.io/Password-Generator',
    screenshot: '/screenshots/password-generator.png',
    featured: false,
    rank: 20,
    accent: 'linear-gradient(135deg, #0071e3 0%, #2997ff 100%)',
  },
  {
    id: 'unit-converter',
    title: 'Unit Converter',
    summary: 'Metric to imperial unit converter with a clean, fast UI.',
    tags: ['JavaScript', 'HTML', 'CSS'],
    repo: 'https://github.com/ChiobiJason/Unit-Converter',
    live: 'https://chiobijason.github.io/Unit-Converter/',
    screenshot: '/screenshots/unit-converter.png',
    featured: false,
    rank: 19,
    accent: 'linear-gradient(135deg, #1d1d1f 0%, #424245 100%)',
  },
  {
    id: 'blackjack-game',
    title: 'BlackJack Game',
    summary: 'A simple blackjack game built for practicing core JS logic and UI updates.',
    tags: ['JavaScript', 'HTML', 'CSS'],
    repo: 'https://github.com/ChiobiJason/Blackjack-Game',
    live: 'https://chiobijason.github.io/Blackjack-Game/',
    screenshot: '/screenshots/blackjack-game.png',
    featured: false,
    rank: 21,
    accent: 'linear-gradient(135deg, #6e6e73 0%, #aeaeb2 100%)',
  },
  {
    id: 'basketball-scoreboard',
    title: 'Basketball Scoreboard',
    summary: 'A small scoreboard app with quick controls and a simple layout.',
    tags: ['JavaScript', 'HTML', 'CSS'],
    repo: 'https://github.com/ChiobiJason/BasketBall-Scoreboard',
    live: 'https://chiobijason.github.io/BasketBall-Scoreboard/',
    screenshot: '/screenshots/basketball-scoreboard.png',
    featured: false,
    rank: 22,
    accent: 'linear-gradient(135deg, #2d2d2f 0%, #636366 100%)',
  },
  {
    id: 'passenger-counter',
    title: 'Passenger Counter App',
    summary: 'A tiny counter app built as a quick UI and state practice project.',
    tags: ['JavaScript', 'HTML', 'CSS'],
    repo: 'https://github.com/ChiobiJason/Passenger-Counter-App',
    live: 'https://passenger-counter-app-jason.netlify.app/',
    screenshot: '/screenshots/passenger-counter.png',
    featured: false,
    rank: 18,
    accent: 'linear-gradient(135deg, #0071e3 0%, #2997ff 100%)',
  },
  {
    id: 'tabletop-games-club',
    title: 'TableTop Games Club',
    summary: 'Static site for a tabletop games club.',
    tags: ['HTML', 'CSS', 'JavaScript'],
    repo: 'https://github.com/ChiobiJason/TableTop-Games-Club',
    live: 'https://chiobijason.github.io/TableTop-Games-Club/',
    screenshot: '/screenshots/tabletop-games-club.png',
    featured: false,
    rank: 17,
    accent: 'linear-gradient(135deg, #1d1d1f 0%, #424245 100%)',
  },
  {
    id: 'hometown',
    title: 'HomeTown',
    summary: 'Hometown project for Lagos with a clean layout and simple interactions.',
    tags: ['HTML', 'CSS', 'JavaScript'],
    repo: 'https://github.com/ChiobiJason/Hometown',
    live: 'https://chiobijason.github.io/Hometown/',
    screenshot: '/screenshots/hometown.png',
    featured: false,
    rank: 16,
    accent: 'linear-gradient(135deg, #6e6e73 0%, #aeaeb2 100%)',
  },
  {
    id: 'digital-business-card',
    title: 'Digital Business Card',
    summary: 'A simple personal card layout built for responsive practice.',
    tags: ['React', 'CSS'],
    repo: 'https://github.com/ChiobiJason/Digital-business-card',
    live: 'https://chiobijason.github.io/Digital-business-card/',
    screenshot: '/screenshots/digital-business-card.png',
    featured: false,
    rank: 14,
    accent: 'linear-gradient(135deg, #2d2d2f 0%, #636366 100%)',
  },
  {
    id: 'ekin',
    title: 'Ekin',
    summary: 'Responsive e-commerce landing page for a fashion and electronics retailer.',
    tags: ['HTML', 'Bootstrap', 'CSS'],
    repo: 'https://github.com/ChiobiJason/Ekin',
    live: 'https://chiobijason.github.io/Ekin/',
    screenshot: '/screenshots/ekin.png',
    featured: false,
    rank: 11,
    accent: 'linear-gradient(135deg, #0071e3 0%, #2997ff 100%)',
  },
]

export const experience = [
  {
    id: 'exp-asa',
    company: 'Augustana Students’ Association, University of Alberta',
    title: 'Full-stack developer',
    location: 'Alberta, Canada',
    period: 'Jan 2026 to Apr 2026',
    bullets: [
      'Two apps (Vue 3, FastAPI, Supabase) with real auth, REST, and layouts that behave on a phone. Live on Vercel and Render for 500+ students.',
      'Policy flows with approvals and versions; inventory at 10,000+ lines with CSV, audit logs, and role-based access.',
    ],
  },
  {
    id: 'exp-margs',
    company: 'Marg’s Computers',
    title: 'IT technician',
    location: 'Alberta, Canada',
    period: 'Aug 2025 to present',
    bullets: [
      'Break/fix for everyday messes: dead drives, Windows 11 installs, flaky Wi‑Fi, weird displays, frozen Mac logins, for both walk-ins and small businesses.',
      'Imaged 20+ laptops and mini PCs, moved data between machines, and broke down ~100 units for recycling when parts were worth saving.',
    ],
  },
  {
    id: 'exp-opendoors',
    company: 'The Open Doors',
    title: 'Administrative assistant',
    location: 'Alberta, Canada',
    period: 'Aug 2025 to Dec 2025',
    bullets: [
      'Kept the office moving: forms, filing, mail, so the team could stay with youth and families instead of paperwork.',
    ],
  },
  {
    id: 'exp-pran',
    company: 'Partnership for Research with African Newcomers (PRAN)',
    title: 'Data visualization specialist',
    location: 'Alberta, Canada',
    period: 'May 2025 to Aug 2025',
    bullets: [
      'R Shiny dashboards that actually sped up analysis: reactive bits, less copy-paste, fewer round trips.',
      'Cleaner charts and cleaner tables for research that leans on census-style data.',
    ],
  },
  {
    id: 'exp-ta',
    company: 'University of Alberta',
    title: 'Teaching assistant',
    location: 'Alberta, Canada',
    period: 'Aug 2024 to Apr 2026',
    bullets: [
      'Weekly labs and one-on-ones for 30+ students a term; graded 100+ things a term with real comments on Canvas and GitHub Classroom.',
    ],
  },
  {
    id: 'exp-grounds',
    company: 'University of Alberta',
    title: 'Summer student, grounds keeper',
    location: 'Alberta, Canada',
    period: 'May 2025 to Aug 2025',
    bullets: [
      'Outdoor upkeep, gear, and odd jobs with facilities when the campus was busy.',
    ],
  },
  {
    id: 'exp-recreation',
    company: 'University of Alberta',
    title: 'Campus recreational facilitator',
    location: 'Alberta, Canada',
    period: 'Aug 2023 to Apr 2026',
    bullets: [
      'Gym and rec spaces during rush hours: set up gear, keep things safe, help people at the desk.',
    ],
  },
  {
    id: 'exp-mcd',
    company: 'McDonald’s',
    title: 'Customer service representative',
    location: 'Alberta, Canada',
    period: 'Jun 2023 to Dec 2025',
    bullets: [
      'Line, grill-adjacent tasks, and customers in a hurry; helped train new people on the rhythm of a shift.',
    ],
  },
  {
    id: 'exp-kfc',
    company: 'KFC',
    title: 'Team member',
    location: 'Alberta, Canada',
    period: 'Jan 2023 to Dec 2025',
    bullets: [
      'Front counter and drive-through, keeping the lane moving and the station clean when it was slammed.',
    ],
  },
  {
    id: 'exp-rccg',
    company: 'RCCG Mount Zion Camrose',
    title: 'Frontend developer',
    location: 'Alberta, Canada',
    period: 'Aug 2022 to Sep 2024',
    bullets: [
      'WordPress rebuild: fewer outages after untangling plugins and hosting quirks.',
      'Tighter layout and navigation; content editors could publish faster after we simplified the CMS path.',
    ],
  },
  {
    id: 'exp-mfm',
    company: 'MFM GH Teens',
    title: 'Frontend developer',
    location: 'Accra, Ghana',
    period: 'Jan 2022 to Aug 2022',
    bullets: [
      'A custom site with forums and resources so teens had a place to show up online.',
      'Handed off docs and a short training so the team could update it without me.',
    ],
  },
]

export const references = [
  {
    id: 'rosanna-heise',
    name: 'Rosanna Heise',
    title: 'Associate Lecturer',
    org: 'University of Alberta',
    phone: '+1 (780) 679-1674',
    email: 'rosanna@ualberta.ca',
  },
  {
    id: 'heidi-hoernig',
    name: 'Heidi Hoernig',
    title: 'Senior Manager',
    org: 'Partnership for Research with African Newcomers (PRAN)',
    phone: '',
    email: 'hoernig@ualberta.ca',
  },
  {
    id: 'margaret-pearson',
    name: 'Margaret Pearson',
    title: 'Owner',
    org: 'Marg’s Computers',
    phone: '+1 (780) 678-2338',
    email: 'margjp@mail.com',
  },
  {
    id: 'mi-young-kim',
    name: 'Mi-Young Kim',
    title: 'Associate Professor',
    org: 'University of Alberta',
    phone: '',
    email: 'miyoung2@ualberta.ca',
  },
  {
    id: 'kelsy-haesloop',
    name: 'Kelsy Haesloop',
    title: 'Student Experience Coordinator, Recreation',
    org: 'Augustana Fitness Centre',
    phone: '+1 (780) 722-7611',
    email: '',
  },
  {
    id: 'dianne-ocliaso',
    name: 'Dianne Ocliaso',
    title: 'Restaurant General Manager',
    org: 'KFC Camrose',
    phone: '+1 (368) 882-1356',
    email: '',
  },
  {
    id: 'dallas-thomas',
    name: 'Dallas Thomas',
    title: 'Associate Professor',
    org: 'University of Alberta',
    phone: '+1 (403) 849-1977',
    email: '',
  },
  {
    id: 'evita-echague',
    name: 'Evita Echague',
    title: "Manager",
    org: "McDonald's Camrose",
    phone: '+1 (780) 226-5523',
    email: '',
  },
  {
    id: 'randy-stumpf',
    name: 'Randy Stumpf',
    title: 'Manager, Augustana Facilities',
    org: 'USOF Augustana Maintenance',
    phone: '+1 (708) 878-1806',
    email: 'rstumpf@ualberta.ca',
  },
]

export const about = {
  headline: 'Background',
  paragraphs: [
    'I graduated from the University of Alberta with a B.Sc. in Computer Science (Class of 2026) and a minor in Mathematics. Coursework covered algorithms, software engineering, OOP, operating systems, AI, and web development.',
    "These days I think of myself as a software engineer first: I still like owning a feature from schema and API routes to what someone actually clicks, and I'm fine being the person who answers when something breaks in prod.",
  ],
  highlights: [
    {
      label: 'Languages',
      value: 'Java, Python, PHP, JavaScript, TypeScript, HTML/CSS, C, C++, SQL, R',
    },
    {
      label: 'Frameworks',
      value: 'React, Vue 3, Next.js, Node.js, FastAPI, Spring Boot, Tailwind, Bootstrap',
    },
    {
      label: 'Data and cloud',
      value: 'PostgreSQL, Supabase, AWS, Docker, Vercel, Render, REST',
    },
    {
      label: 'Tools',
      value: 'VS Code, IntelliJ, Git/GitHub, Figma, WordPress, RStudio, CI/CD',
    },
  ],
}
